// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for DynamoBridgeFunction
 */
export interface DynamoBridgeFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/core/database/dynamo-bridge.
 */
export class DynamoBridgeFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: DynamoBridgeFunctionProps) {
    super(scope, id, {
      description: 'src/core/database/dynamo-bridge.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs22.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/core/database/dynamo-bridge.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}