// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for RegisterSlashCommandFunction
 */
export interface RegisterSlashCommandFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/shared/discord-slash-command/register-slash-command.
 */
export class RegisterSlashCommandFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: RegisterSlashCommandFunctionProps) {
    super(scope, id, {
      description: 'src/shared/discord-slash-command/register-slash-command.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs22.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/shared/discord-slash-command/register-slash-command.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}