name: "Prepare Environment"
description: "Installs Node.js, pnpm, and project dependencies"
runs:
  using: "composite"
  steps:
    - name: Cache Bun dependencies
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Set up bun
      uses: oven-sh/setup-bun@v2

    - name: Set up Node
      uses: actions/setup-node@v6
      with:
        node-version: "22"

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
