name: Deploy CDK

on:
  push:
    branches: [main]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  diff:
    runs-on: ubuntu-latest
    env:
      APP_ENV: prod
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Prepare environment
        uses: ./.github/workflows/prepare

      - name: Assume GHA role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.PROD_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Diff CDK
        run: npx cdk diff ${APP_ENV}/*

  deploy:
    environment: prod
    runs-on: ubuntu-latest
    env:
      APP_ENV: prod
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Prepare environment
        uses: ./.github/workflows/prepare

      - name: Assume GHA role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.PROD_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy CDK
        run: npx cdk deploy ${APP_ENV}/* --require-approval never
